# Python知识点

## os.path.join()

In [2]:
import os
# 字符串模板
print("I am %s. I'm %d years old" % ('Vamei', 99))  # %s 字符 格式符 %d 整数格式符

I am Vamei. I'm 99 years old


In [3]:
base = os.path.join('home', "Annotations", "%s.xml");
print(base)
print(base % "001")

home/Annotations/%s.xml
home/Annotations/001.xml


## tqdm()

In [4]:
from tqdm import tqdm

for item in tqdm(range(100)):
    # do something
    pass

100%|█████████████████████████████████████| 100/100 [00:00<00:00, 934143.43it/s]


In [6]:
lt = ['a', 'b', 'c']
for i, item in enumerate(lt):
    print(i, item)

0 a
1 b
2 c


In [7]:
lt = ['a', 'b', 'c']
for i, item in enumerate(tqdm(lt)):
    print(i, item)

100%|██████████████████████████████████████████| 3/3 [00:00<00:00, 14614.30it/s]

0 a
1 b
2 c


## assert()

不满足expression条件的话报错；

In [ ]:
assert expression [, arguments]

等价于

In [ ]:
if not expression:
    raise AssertionError(arguments)

In [13]:
assert 1==1
print('everything is good')

everything is good


In [15]:
assert 1==2, 'not good'
print('everything is good')

AssertionError: not good

## zip()

zip()函数用于将可迭代的对象作为参数，将对象中对应的元素打包成一个个元组，然后返回由这些元组组成的可迭代对象。
利用*号操作符，可以将元组解压。

In [22]:
a = [1, 2, 3]
b = [4, 5, 6]
zipped = zip(a, b)  # 打包为元组的列表
zipped

In [23]:
list(zipped)

[(1, 4), (2, 5), (3, 6)]

In [27]:
list(zip(*zipped))  # 与zip相反，*zipped可以理解为解压，返回二维矩阵式

[]

In [28]:
c = [(1, 2), (3, 4)]
list(zip(*c))

[(1, 3), (2, 4)]

## map()

map()函数语法：

In [ ]:
map(function, iterable, ...)

map()会根据提供的函数对指定序列作映射，返回值为：可迭代对象

In [29]:
def square(x):  # 计算平方数
    return x ** 2

list(map(square, [1, 2, 3, 4, 5]))  # 计算列表各个元素的平方

[1, 4, 9, 16, 25]

## array[..., n]

只看最后一个维度，按列选取

In [31]:
import numpy as np
y = np.array([[[10, 12, 48, 60],
              [10, 20, 40, 50],
              [1, 2, 3, 4]]])
print(y.shape)
y[..., 2]  # 取第一列 所有gt框的xmin

(1, 3, 4)


array([[48, 40,  3]])

In [34]:
y = np.arange(24).reshape(2, 3, 4)
y

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [35]:
y[..., 0]

array([[ 0,  4,  8],
       [12, 16, 20]])

# Pytorch知识点

In [37]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import math
import matplotlib.pyplot as plt

## Tensor

#### torch.tensor.type()

查看张量类型：tensor.dtype
张量类型转换：tensor.type()

In [38]:
tensor = torch.rand((2, 4))
print(tensor)
print(tensor.dtype)

tensor([[0.0571, 0.3517, 0.2811, 0.0866],
        [0.5100, 0.3208, 0.3378, 0.2282]])
torch.float32


In [39]:
tensor = tensor.type(torch.float64)
print(tensor)
print(tensor.dtype)

tensor([[0.0571, 0.3517, 0.2811, 0.0866],
        [0.5100, 0.3208, 0.3378, 0.2282]], dtype=torch.float64)
torch.float64


#### torch.from_numpy()

将numpy格式数据转换成torch.tensor

torch.numpy():将tensor转换成numpy数据

In [40]:
# numpy的array与torch的tensor的转换
np_data = np.arange(6).reshape((2, 3))
np_data

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
torch_data = torch.from_numpy(np_data)
torch_data

tensor([[0, 1, 2],
        [3, 4, 5]])

In [42]:
tensor2array = torch_data.numpy()
tensor2array

array([[0, 1, 2],
       [3, 4, 5]])